# Generated by Django 2.0.4 on 2020-08-10 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=399)),
            ],
        ),
        migrations.RemoveField(
            model_name='whishlist',
            name='items',
        ),
        migrations.RemoveField(
            model_name='whishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Whishlist',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(to='shop.Item'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
